// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMI1vtRhiE6xtlcyapbAOWnBlHLIiDnTk',
    appId: '1:620520844342:web:7143291591eb4118d8bc97',
    messagingSenderId: '620520844342',
    projectId: 'internsheep-ape',
    authDomain: 'internsheep-ape.firebaseapp.com',
    storageBucket: 'internsheep-ape.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWj2Br0_6RPxbc2HOAQZEr1DTjh23Xg8Y',
    appId: '1:620520844342:android:cbc59e5d7741ca8ad8bc97',
    messagingSenderId: '620520844342',
    projectId: 'internsheep-ape',
    storageBucket: 'internsheep-ape.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBka0DPW7MQU4mHte1Yfdht4IkeWpGl6MQ',
    appId: '1:620520844342:ios:9300a7a084d78587d8bc97',
    messagingSenderId: '620520844342',
    projectId: 'internsheep-ape',
    storageBucket: 'internsheep-ape.appspot.com',
    iosClientId: '620520844342-vtutclmjmokf9ir0f8f1f3lj2at7v7hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBka0DPW7MQU4mHte1Yfdht4IkeWpGl6MQ',
    appId: '1:620520844342:ios:9300a7a084d78587d8bc97',
    messagingSenderId: '620520844342',
    projectId: 'internsheep-ape',
    storageBucket: 'internsheep-ape.appspot.com',
    iosClientId: '620520844342-vtutclmjmokf9ir0f8f1f3lj2at7v7hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz',
  );
}
